# Generated by Django 3.1.2 on 2020-11-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('district', models.CharField(choices=[('idukki', 'Idukki'), ('kottayam', 'Kottayam'), ('kollam', 'Kollam'), ('palakkad', 'Palakkad'), ('kasaragod', 'Kasaragod'), ('pathanamthitta', 'Pathanamthitta'), ('thrissur', 'Thrissur'), ('kozhikode', 'Kozhikode'), ('ernakulam', 'Ernakulam'), ('malappuram', 'Malappuram'), ('kannur', 'Kannur'), ('alappuzha', 'Alappuzha'), ('wayanad', 'Wayanad'), ('thiruvananthapuram', 'Thiruvananthapuram')], max_length=20)),
                ('category', models.CharField(choices=[('senior', 'senior'), ('school', 'school'), ('campus', 'campus')], max_length=10)),
            ],
        ),
    ]
