# Generated by Django 3.1.2 on 2020-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event_1',
            field=models.CharField(choices=[('poem', 'poem'), ('story', 'story'), ('dance', 'dance')], default='story', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='event_2',
            field=models.CharField(choices=[('poem', 'poem'), ('story', 'story'), ('dance', 'dance')], default='story', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='event_3',
            field=models.CharField(choices=[('poem', 'poem'), ('story', 'story'), ('dance', 'dance')], default='story', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('school', 'school'), ('campus', 'campus'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('wayanad', 'Wayanad'), ('thrissur', 'Thrissur'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kozhikode', 'Kozhikode'), ('alappuzha', 'Alappuzha'), ('pathanamthitta', 'Pathanamthitta'), ('palakkad', 'Palakkad'), ('kasaragod', 'Kasaragod'), ('ernakulam', 'Ernakulam'), ('malappuram', 'Malappuram'), ('idukki', 'Idukki'), ('kollam', 'Kollam'), ('kottayam', 'Kottayam'), ('kannur', 'Kannur')], max_length=20),
        ),
    ]
