# Generated by Django 3.1.3 on 2020-11-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20201106_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event_1',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event_2',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event_3',
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('senior', 'senior'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kasaragod', 'Kasaragod'), ('idukki', 'Idukki'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('kannur', 'Kannur'), ('wayanad', 'Wayanad'), ('palakkad', 'Palakkad'), ('kollam', 'Kollam'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('thrissur', 'Thrissur'), ('malappuram', 'Malappuram'), ('alappuzha', 'Alappuzha'), ('ernakulam', 'Ernakulam'), ('pathanamthitta', 'Pathanamthitta')], max_length=20),
        ),
        migrations.CreateModel(
            name='Paricipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.participant')),
            ],
        ),
    ]
