# Generated by Django 3.1.2 on 2020-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201107_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('school', 'school'), ('campus', 'campus'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kannur', 'Kannur'), ('ernakulam', 'Ernakulam'), ('kottayam', 'Kottayam'), ('malappuram', 'Malappuram'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad'), ('idukki', 'Idukki'), ('kasaragod', 'Kasaragod'), ('pathanamthitta', 'Pathanamthitta'), ('palakkad', 'Palakkad'), ('kollam', 'Kollam'), ('kozhikode', 'Kozhikode'), ('alappuzha', 'Alappuzha')], max_length=20),
        ),
    ]
