# Generated by Django 3.1.2 on 2020-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201107_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('senior', 'senior'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kollam', 'Kollam'), ('alappuzha', 'Alappuzha'), ('palakkad', 'Palakkad'), ('pathanamthitta', 'Pathanamthitta'), ('malappuram', 'Malappuram'), ('kozhikode', 'Kozhikode'), ('thrissur', 'Thrissur'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('wayanad', 'Wayanad'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernakulam', 'Ernakulam'), ('thiruvananthapuram', 'Thiruvananthapuram')], max_length=20),
        ),
    ]
