# Generated by Django 3.1.2 on 2020-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20201107_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('pathanamthitta', 'Pathanamthitta'), ('malappuram', 'Malappuram'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('thrissur', 'Thrissur'), ('kozhikode', 'Kozhikode'), ('alappuzha', 'Alappuzha'), ('kollam', 'Kollam'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('idukki', 'Idukki'), ('wayanad', 'Wayanad'), ('ernakulam', 'Ernakulam'), ('palakkad', 'Palakkad'), ('kottayam', 'Kottayam')], max_length=20),
        ),
    ]
