# Generated by Django 3.1.2 on 2020-11-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20201107_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('school', 'school'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kasaragod', 'Kasaragod'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('palakkad', 'Palakkad'), ('alappuzha', 'Alappuzha'), ('idukki', 'Idukki'), ('pathanamthitta', 'Pathanamthitta'), ('kollam', 'Kollam'), ('malappuram', 'Malappuram'), ('wayanad', 'Wayanad'), ('thrissur', 'Thrissur'), ('kannur', 'Kannur'), ('ernakulam', 'Ernakulam')], max_length=20),
        ),
    ]
