# Generated by Django 3.1.2 on 2020-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20201107_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('senior', 'senior'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kozhikode', 'Kozhikode'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kannur', 'Kannur'), ('alappuzha', 'Alappuzha'), ('malappuram', 'Malappuram'), ('ernakulam', 'Ernakulam'), ('kottayam', 'Kottayam'), ('kollam', 'Kollam'), ('pathanamthitta', 'Pathanamthitta'), ('kasaragod', 'Kasaragod'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad'), ('idukki', 'Idukki'), ('palakkad', 'Palakkad')], max_length=20),
        ),
    ]
