# Generated by Django 3.1.2 on 2020-11-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20201107_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('senior', 'senior'), ('school', 'school'), ('campus', 'campus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kannur', 'Kannur'), ('malappuram', 'Malappuram'), ('ernakulam', 'Ernakulam'), ('alappuzha', 'Alappuzha'), ('pathanamthitta', 'Pathanamthitta'), ('thrissur', 'Thrissur'), ('palakkad', 'Palakkad'), ('wayanad', 'Wayanad'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kasaragod', 'Kasaragod'), ('kollam', 'Kollam'), ('idukki', 'Idukki')], max_length=20),
        ),
    ]
