# Generated by Django 3.1.2 on 2020-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20201107_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paricipation',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('school', 'school'), ('senior', 'senior'), ('campus', 'campus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('palakkad', 'Palakkad'), ('kannur', 'Kannur'), ('pathanamthitta', 'Pathanamthitta'), ('wayanad', 'Wayanad'), ('ernakulam', 'Ernakulam'), ('kollam', 'Kollam'), ('idukki', 'Idukki'), ('thrissur', 'Thrissur'), ('kozhikode', 'Kozhikode'), ('alappuzha', 'Alappuzha'), ('kasaragod', 'Kasaragod'), ('malappuram', 'Malappuram'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kottayam', 'Kottayam')], max_length=20),
        ),
    ]
