# Generated by Django 3.1.2 on 2020-11-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20201107_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paricipation',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('school', 'school'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kottayam', 'Kottayam'), ('kasaragod', 'Kasaragod'), ('kozhikode', 'Kozhikode'), ('malappuram', 'Malappuram'), ('palakkad', 'Palakkad'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('pathanamthitta', 'Pathanamthitta'), ('alappuzha', 'Alappuzha'), ('thrissur', 'Thrissur'), ('kannur', 'Kannur'), ('ernakulam', 'Ernakulam'), ('idukki', 'Idukki'), ('kollam', 'Kollam'), ('wayanad', 'Wayanad')], max_length=20),
        ),
    ]
