# Generated by Django 3.1.2 on 2020-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20201107_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('senior', 'senior'), ('school', 'school'), ('campus', 'campus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('palakkad', 'Palakkad'), ('alappuzha', 'Alappuzha'), ('kozhikode', 'Kozhikode'), ('idukki', 'Idukki'), ('wayanad', 'Wayanad'), ('kollam', 'Kollam'), ('kottayam', 'Kottayam'), ('ernakulam', 'Ernakulam'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('malappuram', 'Malappuram'), ('pathanamthitta', 'Pathanamthitta'), ('thrissur', 'Thrissur'), ('kasaragod', 'Kasaragod'), ('kannur', 'Kannur')], max_length=20),
        ),
    ]
