# Generated by Django 3.1.2 on 2020-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20201107_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paricipation',
            new_name='Participation',
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('school', 'school'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('palakkad', 'Palakkad'), ('wayanad', 'Wayanad'), ('kottayam', 'Kottayam'), ('alappuzha', 'Alappuzha'), ('pathanamthitta', 'Pathanamthitta'), ('kollam', 'Kollam'), ('kannur', 'Kannur'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kasaragod', 'Kasaragod'), ('ernakulam', 'Ernakulam'), ('malappuram', 'Malappuram'), ('idukki', 'Idukki'), ('kozhikode', 'Kozhikode'), ('thrissur', 'Thrissur')], max_length=20),
        ),
    ]
