# Generated by Django 3.1.2 on 2020-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20201107_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('senior', 'senior'), ('campus', 'campus'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('palakkad', 'Palakkad'), ('kasaragod', 'Kasaragod'), ('ernakulam', 'Ernakulam'), ('kottayam', 'Kottayam'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('idukki', 'Idukki'), ('kollam', 'Kollam'), ('malappuram', 'Malappuram'), ('wayanad', 'Wayanad'), ('kozhikode', 'Kozhikode'), ('kannur', 'Kannur'), ('pathanamthitta', 'Pathanamthitta'), ('alappuzha', 'Alappuzha'), ('thrissur', 'Thrissur')], max_length=20),
        ),
    ]
