# Generated by Django 3.1.2 on 2020-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20201107_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participation',
            new_name='Paricipation',
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('alappuzha', 'Alappuzha'), ('ernakulam', 'Ernakulam'), ('kozhikode', 'Kozhikode'), ('kollam', 'Kollam'), ('malappuram', 'Malappuram'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad'), ('idukki', 'Idukki'), ('kottayam', 'Kottayam'), ('palakkad', 'Palakkad'), ('kasaragod', 'Kasaragod'), ('pathanamthitta', 'Pathanamthitta'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kannur', 'Kannur')], max_length=20),
        ),
    ]
