# Generated by Django 3.1.2 on 2020-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20201107_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('alappuzha', 'Alappuzha'), ('thrissur', 'Thrissur'), ('idukki', 'Idukki'), ('pathanamthitta', 'Pathanamthitta'), ('palakkad', 'Palakkad'), ('kannur', 'Kannur'), ('kollam', 'Kollam'), ('malappuram', 'Malappuram'), ('kottayam', 'Kottayam'), ('ernakulam', 'Ernakulam'), ('kasaragod', 'Kasaragod')], max_length=20),
        ),
    ]
