# Generated by Django 3.1.2 on 2020-11-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20201107_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('campus', 'campus'), ('senior', 'senior'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('thrissur', 'Thrissur'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('kollam', 'Kollam'), ('palakkad', 'Palakkad'), ('alappuzha', 'Alappuzha'), ('malappuram', 'Malappuram'), ('idukki', 'Idukki'), ('pathanamthitta', 'Pathanamthitta'), ('ernakulam', 'Ernakulam')], max_length=20),
        ),
    ]
