# Generated by Django 3.1.2 on 2020-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20201108_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('senior', 'senior'), ('school', 'school'), ('campus', 'campus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('kasaragod', 'Kasaragod'), ('kozhikode', 'Kozhikode'), ('pathanamthitta', 'Pathanamthitta'), ('ernakulam', 'Ernakulam'), ('thrissur', 'Thrissur'), ('kollam', 'Kollam'), ('wayanad', 'Wayanad'), ('palakkad', 'Palakkad'), ('alappuzha', 'Alappuzha'), ('kannur', 'Kannur'), ('malappuram', 'Malappuram')], max_length=20),
        ),
    ]
