# Generated by Django 3.1.2 on 2020-11-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20201108_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('school', 'school'), ('campus', 'campus'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(choices=[('alappuzha', 'Alappuzha'), ('wayanad', 'Wayanad'), ('thrissur', 'Thrissur'), ('ernakulam', 'Ernakulam'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('idukki', 'Idukki'), ('kasaragod', 'Kasaragod'), ('palakkad', 'Palakkad'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('kannur', 'Kannur'), ('malappuram', 'Malappuram'), ('pathanamthitta', 'Pathanamthitta'), ('kollam', 'Kollam')], max_length=20),
        ),
    ]
